sudo: false

language: python

addons:
  apt:
    packages:
      - libeigen3-dev

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - pip install -U pip wheel setuptools
  - pip install numpy cython nose
  - python -V

install:
  - pip install .

script:
  - cd $HOME
  - mkdir empty
  - cd empty
  - nosetests ceygen

cache:
  directories:
    - $HOME/.cache/pip
