language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

install:
  - sudo apt-get install -qq libeigen3-dev
  - pip install cython --use-mirrors
  # Python 3 environment on travis doesn't see python3-numpy package, install manually
  - test ${TRAVIS_PYTHON_VERSION%%.*} = 3 && pip install numpy --use-mirrors

script:
  - python setup.py -v test
